#!/usr/bin/env python3
# Emit the gr-ieee802-11 C++ header of all 12 IEEE 802.11 QC-LDPC base matrices from
# sdr2wifi/ldpc.py CODES, so the fork's TX encoder isn't hand-transcribed. Run:
#   python3 tools/gen_ldpc_bases.py > /path/to/gr-ieee802-11/lib/ldpc_bases.h
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
import ldpc

print("// Generated by sdr2wifi/tools/gen_ldpc_bases.py from ldpc.py CODES -- do not edit.")
print("// The 12 IEEE 802.11 QC-LDPC base matrices (rows x 24 blocks, subblock size Z).")
print("#ifndef INCLUDED_IEEE802_11_LDPC_BASES_H")
print("#define INCLUDED_IEEE802_11_LDPC_BASES_H")
print("namespace gr { namespace ieee802_11 {")
print("struct ldpc_code { const int* base; int rows; int Z; int n; int kbits; };")
order = ["R12_648", "R23_648", "R34_648", "R56_648",
         "R12_1296", "R23_1296", "R34_1296", "R56_1296",
         "R12_1944", "R23_1944", "R34_1944", "R56_1944"]
for name in order:
    base, Z = ldpc.CODES[name]
    rows = len(base)
    flat = ",".join(str(v) for row in base for v in row)
    print(f"static const int LDPC_QC_{name}[{rows}*24] = {{{flat}}};")
print()
print("// Lookup by native length n and rate (rnum/rden).")
print("inline ldpc_code ldpc_code_for(int n, int rnum, int rden) {")
print("    struct E { int n, rnum, rden; const int* base; int rows; int Z; };")
print("    static const E tab[] = {")
for name in order:
    base, Z = ldpc.CODES[name]
    rows = len(base)
    n = 24 * Z
    R = (24 - rows) / 24  # rows = n-k blocks; k blocks = 24-rows
    # rate fraction from name
    rnum, rden = {"R12": (1, 2), "R23": (2, 3), "R34": (3, 4), "R56": (5, 6)}[name.split("_")[0]]
    print(f"        {{{n}, {rnum}, {rden}, LDPC_QC_{name}, {rows}, {Z}}},")
print("    };")
print("    for (auto& e : tab)")
print("        if (e.n == n && e.rnum == rnum && e.rden == rden)")
print("            return ldpc_code{ e.base, e.rows, e.Z, e.n, e.n - e.rows * e.Z };")
print("    return ldpc_code{ nullptr, 0, 0, 0, 0 };")
print("}")
print("} }")
print("#endif")
